
services:
  - type: web
    name: ai-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
